name: E

on:
repository_dispatch:
   types: {i}

jobs:
sj:
   runs-on: ubuntu-latest
   steps:
   - name: C A
       uses: actions/checkout@v2
       with:
       path: main
   - name: C M A
       run: |
       cd ./main/
       ls ${GITHUB_WORKSPACE}
       echo ${GITHUB_WORKSPACE}
       pwd
       echo "main is done..."

   - name: yq-i
       uses: actions/checkout@v2
       with:
       repository: dsjena/yq-a
       token: ${{ secrets.SUPER_SECRET }}
       path: yq-i
   - name: S A
       uses: actions/setup-python@v2
       with:
       python-version: '3.8'
   - name: I D A
       run: |
       cd ./yq-i/
       python -m pip install --upgrade pip
       pip install -r requirements.txt
   - name: AC A
       run: |
       cd ./yq-i/
       dtt=Sun Jan 16 18:25:17 IST 2022
       echo ${GITHUB_WORKSPACE}
       echo "${dtt}" 
       echo "${dtt}" >> recieved.md
       bash make-rdme.sh >> log.txt 2>&1
       sh all-run-group.sh 
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git add .
       git diff-index --quiet HEAD || git commit -m "Load YH" -a
       git push
